# Generated by Django 4.2.6 on 2023-10-14 18:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="joined_date",
            field=models.DateField(
                default=datetime.datetime(2023, 10, 15, 0, 0, 55, 60760)
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="phone",
            field=models.IntegerField(default="9285741451"),
        ),
    ]
