# Generated by Django 4.2.6 on 2023-10-15 08:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0003_alter_member_joined_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="joined_date",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 10, 15, 8, 13, 53, 771907, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
