# Generated by Django 4.2.6 on 2023-10-15 09:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0004_alter_member_joined_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="slug",
            field=models.SlugField(default=""),
        ),
        migrations.AlterField(
            model_name="member",
            name="joined_date",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 10, 15, 9, 16, 6, 708299, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
