# Generated by Django 4.2.6 on 2023-10-16 13:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0006_alter_member_joined_date_alter_member_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=255)),
                ("message", models.CharField(max_length=5000)),
            ],
        ),
        migrations.AlterField(
            model_name="member",
            name="joined_date",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 10, 16, 13, 6, 49, 748359, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
