# Generated by Django 4.2.6 on 2023-10-17 06:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0007_contactus_alter_member_joined_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="joined_date",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 10, 17, 6, 40, 59, 364514, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
